In [1]:
import pandas as pd
import numpy as np
import requests
import json
from collections import defaultdict

In [2]:
EMAIL = 'jmeiwb20@gmail.com'
KEY = 'mauvemouse78'
MA = '25'

In [3]:
counties_response = requests.get(f"https://aqs.epa.gov/data/api/list/countiesByState?email={EMAIL}&key={KEY}&state={MA}")
counties = counties_response.json()
counties

{'Header': [{'status': 'Success',
   'request_time': '2026-03-26T01:54:16-04:00',
   'url': 'https://aqs.epa.gov/data/api/list/countiesByState?email=jmeiwb20@gmail.com&key=mauvemouse78&state=25',
   'rows': 14}],
 'Data': [{'code': '001', 'value_represented': 'Barnstable'},
  {'code': '003', 'value_represented': 'Berkshire'},
  {'code': '005', 'value_represented': 'Bristol'},
  {'code': '007', 'value_represented': 'Dukes'},
  {'code': '009', 'value_represented': 'Essex'},
  {'code': '011', 'value_represented': 'Franklin'},
  {'code': '013', 'value_represented': 'Hampden'},
  {'code': '015', 'value_represented': 'Hampshire'},
  {'code': '017', 'value_represented': 'Middlesex'},
  {'code': '019', 'value_represented': 'Nantucket'},
  {'code': '021', 'value_represented': 'Norfolk'},
  {'code': '023', 'value_represented': 'Plymouth'},
  {'code': '025', 'value_represented': 'Suffolk'},
  {'code': '027', 'value_represented': 'Worcester'}]}

In [4]:
bc_response = requests.get(f"https://aqs.epa.gov/data/api/monitors/byCounty?email={EMAIL}&key={KEY}&param=88502&bdate=20150501&edate=20150502&state={MA}&county=001")
bc = bc_response.json()
bc

{'Header': [{'status': 'Success',
   'request_time': '2026-03-26T01:54:17-04:00',
   'url': 'https://aqs.epa.gov/data/api/monitors/byCounty?email=jmeiwb20@gmail.com&key=mauvemouse78&param=88502&bdate=20150501&edate=20150502&state=25&county=001',
   'rows': 1}],
 'Data': [{'state_code': '25',
   'county_code': '001',
   'site_number': '0002',
   'parameter_code': '88502',
   'poc': 1,
   'parameter_name': 'Acceptable PM2.5 AQI & Speciation Mass',
   'open_date': '2001-04-04',
   'close_date': None,
   'concurred_exclusions': None,
   'dominant_source': None,
   'measurement_scale': 'REGIONAL SCALE',
   'measurement_scale_def': '50 TO HUNDREDS KM',
   'monitoring_objective': 'GENERAL/BACKGROUND',
   'last_method_code': '707',
   'last_method_description': 'IMPROVE Module A with Cyclone Inlet-Teflon Filter, 2.2 sq. cm. - GRAVIMETRIC',
   'last_method_begin_date': '2001-04-04',
   'naaqs_primary_monitor': None,
   'qa_primary_monitor': None,
   'monitor_type': 'EPA',
   'networks': 'IMPROVE',
   'monitoring_agency_code': '0745',
   'monitoring_agency': 'National Park Service',
   'si_id': 6931,
   'latitude': 41.975804,
   'longitude': -70.023598,
   'datum': 'WGS84',
   'lat_lon_accuracy': 30.36,
   'elevation': 41.0,
   'probe_height': None,
   'pl_probe_location': None,
   'local_site_name': 'TRURO NATIONAL SEASHORE',
   'address': 'FOX BOTTOM AREA',
   'state_name': 'Massachusetts',
   'county_name': 'Barnstable',
   'city_name': 'Truro',
   'cbsa_code': '12700',
   'cbsa_name': 'Barnstable Town, MA',
   'csa_code': '148',
   'csa_name': 'Boston-Worcester-Providence, MA-RI-NH-CT',
   'tribal_code': None,
   'tribe_name': None}]}

In [5]:
conc = pd.read_csv("annual_conc_by_monitor_2025.csv")

In [6]:
conc.head()

,State Code,County Code,Site Num,Parameter Code,POC,Latitude,Longitude,Datum,Parameter Name,Sample Duration,...,75th Percentile,50th Percentile,10th Percentile,Local Site Name,Address,State Name,County Name,City Name,CBSA Name,Date of Last Change
0,1,3,10,44201,1,30.497478,-87.880258,NAD83,Ozone,1 HOUR,...,0.054,0.045,0.029,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE...",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2025-10-29
1,1,3,10,44201,1,30.497478,-87.880258,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,...,0.049,0.040,0.026,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE...",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2025-10-29
2,1,3,10,44201,1,30.497478,-87.880258,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,...,0.049,0.040,0.026,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE...",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2025-10-29
3,1,3,10,44201,1,30.497478,-87.880258,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,...,0.049,0.040,0.026,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE...",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2025-10-29
4,1,3,10,88101,3,30.497478,-87.880258,NAD83,PM2.5 - Local Conditions,1 HOUR,...,10.000,6.000,1.000,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE...",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2025-10-29

In [7]:
pollutants_tested = conc[["Local Site Name", "Parameter Name", "State Name"]]

In [8]:
tested = defaultdict(dict)
for state in list(set(conc['State Name'])):
    state_df = conc[conc["State Name"] == state]
    for site in list(set(state_df[['Local Site Name']])):
        site_df = state_df[state_df["Local Site Name"] == site]
        params = set(site_df['Parameter Name'])
        tested[state][site] = params

In [9]:
tested = defaultdict(dict)
for i in list(set(conc['State Name'])):
    state_df = conc[conc["State Name"] == i]
    for j in list(set(state_df['Local Site Name'])):
        site_df = state_df[state_df["Local Site Name"] == j]
        params = set(site_df['Parameter Name'])
        tested[i][j] = params

In [10]:
conc.columns

Index(['State Code', 'County Code', 'Site Num', 'Parameter Code', 'POC',
       'Latitude', 'Longitude', 'Datum', 'Parameter Name', 'Sample Duration',
       'Pollutant Standard', 'Metric Used', 'Method Name', 'Year',
       'Units of Measure', 'Event Type', 'Observation Count',
       'Observation Percent', 'Completeness Indicator', 'Valid Day Count',
       'Required Day Count', 'Exceptional Data Count', 'Null Data Count',
       'Primary Exceedance Count', 'Secondary Exceedance Count',
       'Certification Indicator', 'Num Obs Below MDL', 'Arithmetic Mean',
       'Arithmetic Standard Dev', '1st Max Value', '1st Max DateTime',
       '2nd Max Value', '2nd Max DateTime', '3rd Max Value',
       '3rd Max DateTime', '4th Max Value', '4th Max DateTime',
       '1st Max Non Overlapping Value', '1st NO Max DateTime',
       '2nd Max Non Overlapping Value', '2nd NO Max DateTime',
       '99th Percentile', '98th Percentile', '95th Percentile',
       '90th Percentile', '75th Percentile', '50th Percentile',
       '10th Percentile', 'Local Site Name', 'Address', 'State Name',
       'County Name', 'City Name', 'CBSA Name', 'Date of Last Change'],
      dtype='object')

In [11]:
conc["Observation Count"]

0        4141
1        4328
2        4328
3        3071
4        5780
         ...
59149     224
59150    6277
59151    6547
59152    6547
59153    4636
Name: Observation Count, Length: 59154, dtype: int64

In [12]:
tested

defaultdict(dict,
            {'Mississippi': {'Hinds CC': {'Outdoor Temperature',
               'Ozone',
               'PM2.5 - Local Conditions'},
              'Pascagoula': {'Nitric oxide (NO)',
               'Nitrogen dioxide (NO2)',
               'Outdoor Temperature',
               'Oxides of nitrogen (NOx)',
               'Ozone',
               'PM2.5 - Local Conditions',
               'SO2 max 5-min avg',
               'Sulfur dioxide'},
              'Gulfport Youth Court': {'Outdoor Temperature',
               'Ozone',
               'PM2.5 - Local Conditions'},
              'Cleveland Delta State': {'Outdoor Temperature',
               'Ozone',
               'PM2.5 - Local Conditions'},
              'Coffeeville': {'Ozone'},
              'Waveland': {'Outdoor Temperature',
               'Ozone',
               'PM2.5 - Local Conditions'},
              'Hernando': {'Outdoor Temperature',
               'Ozone',
               'PM2.5 - Local Conditions'},
              'Meridian': {'Ozone'},
              'Jackson NCORE': {'Aluminum PM2.5 LC',
               'Ammonium Ion PM2.5 LC',
               'Antimony PM2.5 LC',
               'Arsenic PM2.5 LC',
               'Average Ambient Pressure',
               'Average Ambient Pressure for URG3000N',
               'Average Ambient Temperature',
               'Average Ambient Temperature for URG3000N',
               'Barium PM2.5 LC',
               'Bromine PM2.5 LC',
               'Cadmium PM2.5 LC',
               'Calcium PM2.5 LC',
               'Carbon monoxide',
               'Cerium PM2.5 LC',
               'Cesium PM2.5 LC',
               'Chloride PM2.5 LC',
               'Chlorine PM2.5 LC',
               'Chromium PM2.5 LC',
               'Cobalt PM2.5 LC',
               'Copper PM2.5 LC',
               'EC CSN_Rev Unadjusted PM2.5 LC TOR',
               'EC CSN_Rev Unadjusted PM2.5 LC TOT',
               'EC PM2.5 LC TOR',
               'EC PM2.5 LC TOT',
               'EC1 CSN_Rev Unadjusted PM2.5 LC',
               'EC1 PM2.5 LC',
               'EC2 CSN_Rev Unadjusted PM2.5 LC',
               'EC2 PM2.5 LC',
               'EC3 CSN_Rev Unadjusted PM2.5 LC',
               'EC3 PM2.5 LC',
               'Indium PM2.5 LC',
               'Iron PM2.5 LC',
               'Lead PM2.5 LC',
               'Light Absorption Coeffiecient',
               'Magnesium PM2.5 LC',
               'Manganese PM2.5 LC',
               'Nickel PM2.5 LC',
               'Nitric oxide (NO)',
               'OC CSN_Rev Unadjusted PM2.5 LC TOR',
               'OC CSN_Rev Unadjusted PM2.5 LC TOT',
               'OC PM2.5 LC TOR',
               'OC PM2.5 LC TOT',
               'OC1 CSN_Rev Unadjusted PM2.5 LC',
               'OC1 PM2.5 LC',
               'OC2 CSN_Rev Unadjusted PM2.5 LC',
               'OC2 PM2.5 LC',
               'OC3 CSN_Rev Unadjusted PM2.5 LC',
               'OC3 PM2.5 LC',
               'OC4 CSN_Rev Unadjusted PM2.5 LC',
               'OC4 PM2.5 LC',
               'OP CSN_Rev Unadjusted PM2.5 LC TOR',
               'OP CSN_Rev Unadjusted PM2.5 LC TOT',
               'OP PM2.5 LC TOR',
               'OP PM2.5 LC TOT',
               'Outdoor Temperature',
               'Ozone',
               'PM10 - LC',
               'PM10 Total 0-10um STP',
               'PM10-2.5 - Local Conditions',
               'PM2.5 - Local Conditions',
               'Phosphorus PM2.5 LC',
               'Potassium Ion PM2.5 LC',
               'Potassium PM2.5 LC',
               'Reactive oxides of nitrogen (NOy)',
               'Reconstructed Mass PM2.5 LC',
               'Relative Humidity ',
               'Rubidium PM2.5 LC',
               'SO2 max 5-min avg',
               'Sample Flow Rate CV - Nylon Filter',
               'Sample Flow Rate CV - Quartz Filter',
               'Sample Flow Rate CV - Teflon Filter',
               'Sample Volume',
               'Sample Volume - Nylon Filter',
               'Sample Volume - Quartz Filter',
               'Sample Volume - Teflon Filter',
               'Selenium PM2.5 LC',
               'Silicon PM2.5 LC',
               'Silver PM2.5 LC',
               'Sodium Ion Pm2.5 LC',
               'Sodium PM2.5 LC',
               'Soil PM2.5 LC',
               'Strontium PM2.5 LC',
               'Sulfate PM2.5 LC',
               'Sulfur PM2.5 LC',
               'Sulfur dioxide',
               'Tin PM2.5 LC',
               'Titanium PM2.5 LC',
               'Total Nitrate PM2.5 LC',
               'Vanadium PM2.5 LC',
               'Wind Direction - Resultant',
               'Wind Speed - Resultant',
               'Zinc PM2.5 LC',
               'Zirconium PM2.5 LC'},
              'Hattiesburg': {'Average Ambient Pressure',
               'Average Ambient Temperature',
               'Outdoor Temperature',
               'PM2.5 - Local Conditions',
               'Sample Volume'},
              'TUPELO AIRPORT NEAR OLD NWS OFFICE': {'Ozone'}},
             'Arkansas': {'EAGLE MOUNTAIN': {'Acceptable PM2.5 AQI & Speciation Mass',
               'Aluminum PM2.5 LC',
               'Ammonium Nitrate PM2.5 LC',
               'Ammonium Sulfate PM2.5 LC',
               'Arsenic PM2.5 LC',
               'Bromine PM2.5 LC',
               'Calcium PM2.5 LC',
               'Chloride PM2.5 LC',
               'Chlorine PM2.5 LC',
               'Chromium PM2.5 LC',
               'Copper PM2.5 LC',
               'EC PM2.5 LC TOR',
               'EC1 PM2.5 LC',
               'EC2 PM2.5 LC',
               'EC3 PM2.5 LC',
               'Iron PM2.5 LC',
               'Lead PM2.5 LC',
               'Light Absorption Coeffiecient',
               'Magnesium PM2.5 LC',
               'Manganese PM2.5 LC',
               'Nickel PM2.5 LC',
               'Nitrite PM2.5 LC',
               'OC PM2.5 LC TOR',
               'OC1 PM2.5 LC',
               'OC2 PM2.5 LC',
               'OC3 PM2.5 LC',
               'OC4 PM2.5 LC',
               'OP PM2.5 LC TOR',
               'Organic Carbon Mass PM2.5 LC',
               'Ozone',
               'PM10 - LC',
               'PM10-2.5 - Local Conditions',
               'Phosphorus PM2.5 LC',
               'Potassium PM2.5 LC',
               'Rubidium PM2.5 LC',
               'Selenium PM2.5 LC',
               'Silicon PM2.5 LC',
               'Sodium PM2.5 LC',
               'Soil PM2.5 LC',
               'Strontium PM2.5 LC',
               'Sulfate PM2.5 LC',
               'Sulfur PM2.5 LC',
               'Titanium PM2.5 LC',
               'Total Nitrate PM2.5 LC',
               'Vanadium PM2.5 LC',
               'Zinc PM2.5 LC',
               'Zirconium PM2.5 LC'},
              'DEER': {'Ozone'},
              'EL DORADO': {'Average Ambient Pressure',
               'Average Ambient Temperature',
               'Elapsed Sample Time',
               'PM2.5 - Local Conditions',
               'Sample Flow Rate- CV',
               'Sample Volume'},
              'PARR': {'Aluminum PM2.5 LC',
               'Ammonium Ion PM2.5 LC',
               'Antimony PM2.5 LC',
               'Arsenic PM2.5 LC',
               'Average Ambient Pressure',
               'Average Ambient Pressure for URG3000N',
               'Average Ambient Temperature',
               'Average Ambient Temperature for URG3000N',
               'Barium PM2.5 LC',
               'Bromine PM2.5 LC',
               'Cadmium PM2.5 LC',
               'Calcium PM2.5 LC',
               'Carbon monoxide',
               'Cerium PM2.5 LC',
               'Cesium PM2.5 LC',
               'Chloride PM2.5 LC',
               'Chlorine PM2.5 LC',
               'Chromium PM2.5 LC',
               'Cobalt PM2.5 LC',
               'Copper PM2.5 LC',
               'EC CSN_Rev Unadjusted PM2.5 LC TOR',
               'EC CSN_Rev Unadjusted PM2.5 LC TOT',
               'EC PM2.5 LC TOR',
               'EC PM2.5 LC TOT',
               'EC1 CSN_Rev Unadjusted PM2.5 LC',
               'EC1 PM2.5 LC',
               'EC2 CSN_Rev Unadjusted PM2.5 LC',
               'EC2 PM2.5 LC',
               'EC3 CSN_Rev Unadjusted PM2.5 LC',
               'EC3 PM2.5 LC',
               'Elapsed Sample Time',
               'Indium PM2.5 LC',
               'Iron PM2.5 LC',
               'Lead PM2.5 LC',
               'Light Absorption Coeffiecient',
               'Magnesium PM2.5 LC',
               'Manganese PM2.5 LC',
               'Nickel PM2.5 LC',
               'Nitric oxide (NO)',
               'Nitrogen dioxide (NO2)',
               'OC CSN_Rev Unadjusted PM2.5 LC TOR',
               'OC CSN_Rev Unadjusted PM2.5 LC TOT',
               'OC PM2.5 LC TOR',
               'OC PM2.5 LC TOT',
               'OC1 CSN_Rev Unadjusted PM2.5 LC',
               'OC1 PM2.5 LC',
               'OC2 CSN_Rev Unadjusted PM2.5 LC',
               'OC2 PM2.5 LC',
               'OC3 CSN_Rev Unadjusted PM2.5 LC',
               'OC3 PM2.5 LC',
               'OC4 CSN_Rev Unadjusted PM2.5 LC',
               'OC4 PM2.5 LC',
               'OP CSN_Rev Unadjusted PM2.5 LC TOR',
               'OP CSN_Rev Unadjusted PM2.5 LC TOT',
               'OP PM2.5 LC TOR',
               'OP PM2.5 LC TOT',
               'Outdoor Temperature',
               'Oxides of nitrogen (NOx)',
               'Ozone',
               'PM10 - LC',
               'PM10 Total 0-10um STP',
               'PM10-2.5 - Local Conditions',
               'PM2.5 - Local Conditions',
               'Phosphorus PM2.5 LC',
               'Potassium Ion PM2.5 LC',
               'Potassium PM2.5 LC',
               'Reactive oxides of nitrogen (NOy)',
               'Reconstructed Mass PM2.5 LC',
               'Relative Humidity ',
               'Rubidium PM2.5 LC',
               'SO2 max 5-min avg',
               'Sample Flow Rate CV - Nylon Filter',
               'Sample Flow Rate CV - Quartz Filter',
               'Sample Flow Rate CV - Teflon Filter',
               'Sample Flow Rate- CV',
               'Sample Volume',
               'Sample Volume - Nylon Filter',
               'Sample Volume - Quartz Filter',
               'Sample Volume - Teflon Filter',
               'Selenium PM2.5 LC',
               'Silicon PM2.5 LC',
               'Silver PM2.5 LC',
               'Sodium Ion Pm2.5 LC',
               'Sodium PM2.5 LC',
               'Soil PM2.5 LC',
               'Strontium PM2.5 LC',
               'Sulfate PM2.5 LC',
               'Sulfur PM2.5 LC',
               'Sulfur dioxide',
               'Tin PM2.5 LC',
               'Titanium PM2.5 LC',
               'Total Nitrate PM2.5 LC',
               'Vanadium PM2.5 LC',
               'Wind Direction - Resultant',
               'Wind Speed - Resultant',
               'Zinc PM2.5 LC',
               'Zirconium PM2.5 LC'},
              'DOYLE SPRINGS ROAD': {'Average Ambient Pressure',
               'Average Ambient Temperature',
               'Elapsed Sample Time',
               'PM2.5 - Local Conditions',
               'Sample Flow Rate- CV',
               'Sample Volume'},
              'HOT SPRINGS': {'Average Ambient Pressure',
               'Average Ambient Temperature',
               'Elapsed Sample Time',
               'PM2.5 - Local Conditions',
               'Sample Flow Rate- CV',
               'Sample Volume'},
              'STUTTGART': {'Average Ambient Pressure',
               'Average Ambient Temperature',
               'Elapsed Sample Time',
               'PM2.5 - Local Conditions',
               'Sample Flow Rate- CV',
               'Sample Volume'},
              'CROSSETT': {'Average Ambient Pressure',
               'Average Ambient Temperature',
               'Elapsed Sample Time',
               'PM2.5 - Local Conditions',
               'Sample Flow Rate- CV',
               'Sample Volume'},
              'Upper Buffalo Wilderness': {'Acceptable PM2.5 AQI & Speciation Mass',
               'Aluminum PM2.5 LC',
               'Ammonium Nitrate PM2.5 LC',
               'Ammonium Sulfate PM2.5 LC',
               'Arsenic PM2.5 LC',
               'Bromine PM2.5 LC',
               'Calcium PM2.5 LC',
               'Chloride PM2.5 LC',
               'Chlorine PM2.5 LC',
               'Chromium PM2.5 LC',
               'Copper PM2.5 LC',
               'EC PM2.5 LC TOR',
               'EC1 PM2.5 LC',
               'EC2 PM2.5 LC',
               'EC3 PM2.5 LC',
               'Iron PM2.5 LC',
               'Lead PM2.5 LC',
               'Light Absorption Coeffiecient',
               'Magnesium PM2.5 LC',
               'Manganese PM2.5 LC',
               'Nickel PM2.5 LC',
               'Nitrite PM2.5 LC',
               'OC PM2.5 LC TOR',
               'OC1 PM2.5 LC',
               'OC2 PM2.5 LC',
               'OC3 PM2.5 LC',
               'OC4 PM2.5 LC',
               'OP PM2.5 LC TOR',
               'Organic Carbon Mass PM2.5 LC',
               'PM10 - LC',
               'PM10-2.5 - Local Conditions',
               'Phosphorus PM2.5 LC',
               'Potassium PM2.5 LC',
               'Rubidium PM2.5 LC',
               'Selenium PM2.5 LC',
               'Silicon PM2.5 LC',
               'Sodium PM2.5 LC',
               'Soil PM2.5 LC',
               'Strontium PM2.5 LC',
               'Sulfate PM2.5 LC',
               'Sulfur PM2.5 LC',
               'Titanium PM2.5 LC',
               'Total Nitrate PM2.5 LC',
               'Vanadium PM2.5 LC',
               'Zinc PM2.5 LC',
               'Zirconium PM2.5 LC'},
              'Fayetteville Airport': {'Ozone'},
              'SPRINGDALE': {'Average Ambient Pressure',
               'Average Ambient Temperature',
               'Elapsed Sample Time',
               'Ozone',
               'PM10 Total 0-10um STP',
               'PM2.5 - Local Conditions',
               'Sample Flow Rate- CV',
               'Sample Volume'},
              'NLR AIRPORT': {'Ozone'},
              'NEWPORT': {'Average Ambient Pressure',
               'Average Ambient Temperature',
               'Elapsed Sample Time',
               'PM2.5 - Local Conditions',
               'Sample Flow Rate- CV',
               'Sample Volume'},
              'MARION': {'Average Ambient Pressure',
               'Average Ambient Temperature',
               'Elapsed Sample Time',
               'Nitric oxide (NO)',
               'Nitrogen dioxide (NO2)',
               'Oxides of nitrogen (NOx)',
               'Ozone',
               'PM2.5 - Local Conditions',
               'Sample Flow Rate- CV',
               'Sample Volume'},
              'MENA': {'Average Ambient Pressure',
               'Average Ambient Temperature',
               'Elapsed Sample Time',
               'PM2.5 - Local Conditions',
               'Sample Flow Rate- CV',
               'Sample Volume'},
              'Caddo Valley': {'Ozone'}},
             'Washington': {' PULLMAN - DEXTER AVE 4': {'Acceptable PM2.5 AQI & Speciation Mass',
               'Light scatter'},
              'ABERDEEN - DIVISION ST': {'Acceptable PM2.5 AQI & Speciation Mass',
               'Light scatter'},
              'ENUMCLAW - MUD MTN (Army Corp of Engineers site)': {'Outdoor Temperature',
               'Ozone',
               'Wind Direction - Resultant',
               'Wind Direction - Scalar',
               'Wind Speed - Resultant',
               'Wind Speed - Scalar'},
              'CUSTER - LOOMIS': {'Ozone'},
              'Columbia River Gorge': {'Acceptable PM2.5 AQI & Speciation Mass',
               'Aluminum PM2.5 LC',
               'Ammonium Nitrate PM2.5 LC',
               'Ammonium Sulfate PM2.5 LC',
               'Arsenic PM2.5 LC',
               'Bromine PM2.5 LC',
               'Calcium PM2.5 LC',
               'Chloride PM2.5 LC',
               'Chlorine PM2.5 LC',
               'Chromium PM2.5 LC',
               'Copper PM2.5 LC',
               'EC PM2.5 LC TOR',
               'EC1 PM2.5 LC',
               'EC2 PM2.5 LC',
               'EC3 PM2.5 LC',
               'Iron PM2.5 LC',
               'Lead PM2.5 LC',
               'Light Absorption Coeffiecient',
               'Magnesium PM2.5 LC',
               'Manganese PM2.5 LC',
               'Nickel PM2.5 LC',
               'Nitrite PM2.5 LC',
               'OC PM2.5 LC TOR',
               'OC1 PM2.5 LC',
               'OC2 PM2.5 LC',
               'OC3 PM2.5 LC',
               'OC4 PM2.5 LC',
               'OP PM2.5 LC TOR',
               'Organic Carbon Mass PM2.5 LC',
               'PM10 - LC',
               'PM10-2.5 - Local Conditions',
               'Phosphorus PM2.5 LC',
               'Potassium PM2.5 LC',
               'Rubidium PM2.5 LC',
               'Selenium PM2.5 LC',
               'Silicon PM2.5 LC',
               'Sodium PM2.5 LC',
               'Soil PM2.5 LC',
               'Strontium PM2.5 LC',
               'Sulfate PM2.5 LC',
               'Sulfur PM2.5 LC',
               'Titanium PM2.5 LC',
               'Total Nitrate PM2.5 LC',
               'Vanadium PM2.5 LC',
               'Zinc PM2.5 LC',
               'Zirconium PM2.5 LC'},
              'Confederated Tribes of the Umatilla Indian Reservation': {'Ozone'},
              'TAHOLAH-CHITWIN DRIVE': {'Acceptable PM2.5 AQI & Speciation Mass',
               'Light scatter'},
              'ELLENSBURG - RUBY ST': {'Acceptable PM2.5 AQI & Speciation Mass',
               'Light scatter',
               'PM2.5 - Local Conditions'},
              'Snoqualmie Pass': {'Acceptable PM2.5 AQI & Speciation Mass',
               'Aluminum PM2.5 LC',
               'Ammonium Nitrate PM2.5 LC',
               'Ammonium Sulfate PM2.5 LC',
               'Arsenic PM2.5 LC',
               'Bromine PM2.5 LC',
               'Calcium PM2.5 LC',
               'Chloride PM2.5 LC',
               'Chlorine PM2.5 LC',
               'Chromium PM2.5 LC',
               'Copper PM2.5 LC',
               'EC PM2.5 LC TOR',
               'EC1 PM2.5 LC',
               'EC2 PM2.5 LC',
               'EC3 PM2.5 LC',
               'Iron PM2.5 LC',
               'Lead PM2.5 LC',
               'Light Absorption Coeffiecient',
               'Magnesium PM2.5 LC',
               'Manganese PM2.5 LC',
               'Nickel PM2.5 LC',
               'Nitrite PM2.5 LC',
               'OC PM2.5 LC TOR',
               'OC1 PM2.5 LC',
               'OC2 PM2.5 LC',
               'OC3 PM2.5 LC',
               'OC4 PM2.5 LC',
               'OP PM2.5 LC TOR',
               'Organic Carbon Mass PM2.5 LC',
               'PM10 - LC',
               'PM10-2.5 - Local Conditions',
               'Phosphorus PM2.5 LC',
               'Potassium PM2.5 LC',
               'Rubidium PM2.5 LC',
               'Selenium PM2.5 LC',
               'Silicon PM2.5 LC',
               'Sodium PM2.5 LC',
               'Soil PM2.5 LC',
               'Strontium PM2.5 LC',
               'Sulfate PM2.5 LC',
               'Sulfur PM2.5 LC',
               'Titanium PM2.5 LC',
               'Total Nitrate PM2.5 LC',
               'Vanadium PM2.5 LC',
               'Zinc PM2.5 LC',
               'Zirconium PM2.5 LC'},
              'ROSALIA - JOSEPHINE ST': {'Acceptable PM2.5 AQI & Speciation Mass',
               'Light scatter'},
              'MOSES LAKE - BALSAM ST': {'Acceptable PM2.5 AQI & Speciation Mass',
               'Light scatter'},
              'LEAVENWORTH - EVANS ST': {'Acceptable PM2.5 AQI & Speciation Mass',
               'Light scatter'},
              'Kennewick_S Clodfelter Rd': {'Ozone'},
              'MESA - PEPOIT WAY': {'Acceptable PM2.5 AQI & Speciation Mass',
               'Light scatter'},
              'Pasayten': {'Acceptable PM2.5 AQI & Speciation Mass',
               'Aluminum PM2.5 LC',
               'Ammonium Nitrate PM2.5 LC',
               'Ammonium Sulfate PM2.5 LC',
               'Arsenic PM2.5 LC',
               'Bromine PM2.5 LC',

In [13]:
tested["Utah"]

{'WASHAKIE': {'Barometric pressure',
  'Nitric oxide (NO)',
  'Nitrogen dioxide (NO2)',
  'Outdoor Temperature',
  'Oxides of nitrogen (NOx)',
  'Ozone',
  'Relative Humidity ',
  'Solar radiation',
  'Wind Direction - Resultant',
  'Wind Speed - Scalar'},
 'Lake Park': {'1,2,3-Trimethylbenzene',
  '1,2,4-Trimethylbenzene',
  '1,3,5-Trimethylbenzene',
  '1,3-Butadiene',
  '1-Butene',
  '1-Hexene',
  '1-Pentene',
  '2,2,4-Trimethylpentane',
  '2,2-Dimethylbutane',
  '2,3,4-Trimethylpentane',
  '2,3-Dimethylbutane',
  '2,3-Dimethylpentane',
  '2,4-Dimethylpentane',
  '2-Methylheptane',
  '2-Methylhexane',
  '2-Methylpentane',
  '3-Methylheptane',
  '3-Methylhexane',
  '3-Methylpentane',
  'Acetylene',
  'Barometric pressure',
  'Benzene',
  'Black Carbon PM2.5 at 880 nm',
  'Cyclohexane',
  'Cyclopentane',
  'Ethane',
  'Ethylbenzene',
  'Ethylene',
  'Isobutane',
  'Isopentane',
  'Isoprene',
  'Isopropylbenzene',
  'Methylcyclohexane',
  'Methylcyclopentane',
  'Nitric oxide (NO)',
  'Nitrogen dioxide (NO2)',
  'Outdoor Temperature',
  'Oxides of nitrogen (NOx)',
  'Ozone',
  'PM10 - LC',
  'PM10 Total 0-10um STP',
  'PM2.5 - Local Conditions',
  'Propane',
  'Propylene',
  'Relative Humidity ',
  'Solar radiation',
  'Styrene',
  'Toluene',
  'Total NMOC (non-methane organic compound)',
  'Wind Direction - Scalar',
  'Wind Speed - Scalar',
  'cis-2-Butene',
  'cis-2-Pentene',
  'm-Diethylbenzene',
  'm-Ethyltoluene',
  'm/p Xylene',
  'n-Butane',
  'n-Decane',
  'n-Dodecane',
  'n-Heptane',
  'n-Hexane',
  'n-Nonane',
  'n-Octane',
  'n-Pentane',
  'n-Propylbenzene',
  'n-Undecane',
  'o-Ethyltoluene',
  'o-Xylene',
  'p-Diethylbenzene',
  'p-Ethyltoluene',
  'trans-2-Butene',
  'trans-2-Pentene'},
 'Antelope Island': {'Outdoor Temperature',
  'Relative Humidity ',
  'Wind Direction - Scalar',
  'Wind Speed - Scalar'},
 'Herriman #3': {'Barometric pressure',
  'Nitric oxide (NO)',
  'Nitrogen dioxide (NO2)',
  'Outdoor Temperature',
  'Oxides of nitrogen (NOx)',
  'Ozone',
  'PM10 Total 0-10um STP',
  'PM2.5 - Local Conditions',
  'Relative Humidity ',
  'Solar radiation',
  'Wind Direction - Scalar',
  'Wind Speed - Scalar'},
 'Hurricane': {'Barometric pressure',
  'Nitric oxide (NO)',
  'Nitrogen dioxide (NO2)',
  'Outdoor Temperature',
  'Oxides of nitrogen (NOx)',
  'Ozone',
  'PM2.5 - Local Conditions',
  'Relative Humidity ',
  'Solar radiation',
  'Wind Direction - Scalar',
  'Wind Speed - Scalar'},
 'Hawthorne': {'1,2,3-Trimethylbenzene',
  '1,2,4-Trimethylbenzene',
  '1,3,5-Trimethylbenzene',
  '1,3-Butadiene',
  '1-Butene',
  '1-Hexene',
  '1-Pentene',
  '2,2,4-Trimethylpentane',
  '2,2-Dimethylbutane',
  '2,3,4-Trimethylpentane',
  '2,3-Dimethylbutane',
  '2,3-Dimethylpentane',
  '2,4-Dimethylpentane',
  '2-Methyl-1-pentene',
  '2-Methylheptane',
  '2-Methylhexane',
  '2-Methylpentane',
  '3-Methylheptane',
  '3-Methylhexane',
  '3-Methylpentane',
  'Acetaldehyde',
  'Acetone',
  'Acetylene',
  'Aluminum PM2.5 LC',
  'Ambient Max Temperature',
  'Ambient Min Temperature',
  'Ammonium Ion PM2.5 LC',
  'Antimony PM2.5 LC',
  'Arsenic PM2.5 LC',
  'Average Ambient Pressure',
  'Average Ambient Pressure for URG3000N',
  'Average Ambient Temperature',
  'Average Ambient Temperature for URG3000N',
  'Barium PM2.5 LC',
  'Barometric pressure',
  'Benzaldehyde',
  'Benzene',
  'Bromine PM2.5 LC',
  'Butyraldehyde',
  'Cadmium PM2.5 LC',
  'Calcium PM2.5 LC',
  'Carbon monoxide',
  'Cerium PM2.5 LC',
  'Cesium PM2.5 LC',
  'Chloride PM2.5 LC',
  'Chlorine PM2.5 LC',
  'Chromium PM2.5 LC',
  'Cobalt PM2.5 LC',
  'Copper PM2.5 LC',
  'Crotonaldehyde',
  'Cyclohexane',
  'Cyclopentane',
  'EC CSN_Rev Unadjusted PM2.5 LC TOR',
  'EC CSN_Rev Unadjusted PM2.5 LC TOT',
  'EC PM2.5 LC TOR',
  'EC PM2.5 LC TOT',
  'EC1 CSN_Rev Unadjusted PM2.5 LC',
  'EC1 PM2.5 LC',
  'EC2 CSN_Rev Unadjusted PM2.5 LC',
  'EC2 PM2.5 LC',
  'EC3 CSN_Rev Unadjusted PM2.5 LC',
  'EC3 PM2.5 LC',
  'Elapsed Sample Time',
  'Ethane',
  'Ethylbenzene',
  'Ethylene',
  'Formaldehyde',
  'Hexanaldehyde',
  'Indium PM2.5 LC',
  'Iron PM2.5 LC',
  'Isobutane',
  'Isopentane',
  'Isoprene',
  'Isopropylbenzene',
  'Lead PM2.5 LC',
  'Light Absorption Coeffiecient',
  'Magnesium PM2.5 LC',
  'Manganese PM2.5 LC',
  'Methyl ethyl ketone',
  'Methylcyclohexane',
  'Methylcyclopentane',
  'Mixing Height',
  'NOy - NO',
  'Nickel PM2.5 LC',
  'Nitric oxide (NO)',
  'Nitrogen dioxide (NO2)',
  'OC CSN_Rev Unadjusted PM2.5 LC TOR',
  'OC CSN_Rev Unadjusted PM2.5 LC TOT',
  'OC PM2.5 LC TOR',
  'OC PM2.5 LC TOT',
  'OC1 CSN_Rev Unadjusted PM2.5 LC',
  'OC1 PM2.5 LC',
  'OC2 CSN_Rev Unadjusted PM2.5 LC',
  'OC2 PM2.5 LC',
  'OC3 CSN_Rev Unadjusted PM2.5 LC',
  'OC3 PM2.5 LC',
  'OC4 CSN_Rev Unadjusted PM2.5 LC',
  'OC4 PM2.5 LC',
  'OP CSN_Rev Unadjusted PM2.5 LC TOR',
  'OP CSN_Rev Unadjusted PM2.5 LC TOT',
  'OP PM2.5 LC TOR',
  'OP PM2.5 LC TOT',
  'Outdoor Temperature',
  'Oxides of nitrogen (NOx)',
  'Ozone',
  'PM10 - LC',
  'PM10 Total 0-10um STP',
  'PM10-2.5 - Local Conditions',
  'PM2.5 - Local Conditions',
  'Phosphorus PM2.5 LC',
  'Potassium Ion PM2.5 LC',
  'Potassium PM2.5 LC',
  'Propane',
  'Propionaldehyde',
  'Propylene',
  'Reactive oxides of nitrogen (NOy)',
  'Reconstructed Mass PM2.5 LC',
  'Relative Humidity ',
  'Rubidium PM2.5 LC',
  'Sample Flow Rate CV - Nylon Filter',
  'Sample Flow Rate CV - Quartz Filter',
  'Sample Flow Rate CV - Teflon Filter',
  'Sample Flow Rate- CV',
  'Sample Max Baro Pressure',
  'Sample Min Baro Pressure',
  'Sample Volume',
  'Sample Volume - Nylon Filter',
  'Sample Volume - Quartz Filter',
  'Sample Volume - Teflon Filter',
  'Selenium PM2.5 LC',
  'Silicon PM2.5 LC',
  'Silver PM2.5 LC',
  'Sodium Ion Pm2.5 LC',
  'Sodium PM2.5 LC',
  'Soil PM2.5 LC',
  'Solar radiation',
  'Strontium PM2.5 LC',
  'Styrene',
  'Sulfate PM2.5 LC',
  'Sulfur PM2.5 LC',
  'Sulfur dioxide',
  'Tin PM2.5 LC',
  'Titanium PM2.5 LC',
  'Toluene',
  'Total NMOC (non-methane organic compound)',
  'Total Nitrate PM2.5 LC',
  'Valeraldehyde',
  'Vanadium PM2.5 LC',
  'Wind Direction - Scalar',
  'Wind Speed - Scalar',
  'Zinc PM2.5 LC',
  'Zirconium PM2.5 LC',
  'alpha.-Pinene',
  'beta.-Pinene',
  'cis-2-Butene',
  'cis-2-Pentene',
  'm-Diethylbenzene',
  'm-Ethyltoluene',
  'm/p Xylene',
  'n-Butane',
  'n-Decane',
  'n-Dodecane',
  'n-Heptane',
  'n-Hexane',
  'n-Nonane',
  'n-Octane',
  'n-Pentane',
  'n-Propylbenzene',
  'n-Undecane',
  'o-Ethyltoluene',
  'o-Xylene',
  'p-Diethylbenzene',
  'p-Ethyltoluene',
  'trans-2-Butene',
  'trans-2-Pentene'},
 'Badger Isaland': {'Outdoor Temperature',
  'Relative Humidity ',
  'Wind Direction - Scalar',
  'Wind Speed - Scalar'},
 nan: set(),
 'Bryce Canyon NP': {'Acceptable PM2.5 AQI & Speciation Mass',
  'Aluminum PM2.5 LC',
  'Ammonium Nitrate PM2.5 LC',
  'Ammonium Sulfate PM2.5 LC',
  'Arsenic PM2.5 LC',
  'Bromine PM2.5 LC',
  'Calcium PM2.5 LC',
  'Chloride PM2.5 LC',
  'Chlorine PM2.5 LC',
  'Chromium PM2.5 LC',
  'Copper PM2.5 LC',
  'EC PM2.5 LC TOR',
  'EC1 PM2.5 LC',
  'EC2 PM2.5 LC',
  'EC3 PM2.5 LC',
  'Iron PM2.5 LC',
  'Lead PM2.5 LC',
  'Light Absorption Coeffiecient',
  'Magnesium PM2.5 LC',
  'Manganese PM2.5 LC',
  'Nickel PM2.5 LC',
  'Nitrite PM2.5 LC',
  'OC PM2.5 LC TOR',
  'OC1 PM2.5 LC',
  'OC2 PM2.5 LC',
  'OC3 PM2.5 LC',
  'OC4 PM2.5 LC',
  'OP PM2.5 LC TOR',
  'Organic Carbon Mass PM2.5 LC',
  'PM10 - LC',
  'PM10-2.5 - Local Conditions',
  'Phosphorus PM2.5 LC',
  'Potassium PM2.5 LC',
  'Rubidium PM2.5 LC',
  'Selenium PM2.5 LC',
  'Silicon PM2.5 LC',
  'Sodium PM2.5 LC',
  'Soil PM2.5 LC',
  'Strontium PM2.5 LC',
  'Sulfate PM2.5 LC',
  'Sulfur PM2.5 LC',
  'Titanium PM2.5 LC',
  'Total Nitrate PM2.5 LC',
  'Vanadium PM2.5 LC',
  'Zinc PM2.5 LC',
  'Zirconium PM2.5 LC'},
 'Harrisville': {'Ambient Max Temperature',
  'Ambient Min Temperature',
  'Average Ambient Pressure',
  'Average Ambient Temperature',
  'Barometric pressure',
  'Carbon monoxide',
  'Elapsed Sample Time',
  'Nitric oxide (NO)',
  'Nitrogen dioxide (NO2)',
  'Outdoor Temperature',
  'Oxides of nitrogen (NOx)',
  'Ozone',
  'PM10 Total 0-10um STP',
  'PM2.5 - Local Conditions',
  'Relative Humidity ',
  'Sample Flow Rate- CV',
  'Sample Max Baro Pressure',
  'Sample Min Baro Pressure',
  'Sample Volume',
  'Solar radiation',
  'Wind Direction - Scalar',
  'Wind Speed - Scalar'},
 'Utah Technical Center': {'1,2,3-Trimethylbenzene',
  '1,2,4-Trimethylbenzene',
  '1,3,5-Trimethylbenzene',
  '1,3-Butadiene',
  '1-Butene',
  '1-Hexene',
  '1-Pentene',
  '2,2,4-Trimethylpentane',
  '2,2-Dimethylbutane',
  '2,3,4-Trimethylpentane',
  '2,3-Dimethylbutane',
  '2,3-Dimethylpentane',
  '2,4-Dimethylpentane',
  '2-Methylheptane',
  '2-Methylhexane',
  '2-Methylpentane',
  '3-Methylheptane',
  '3-Methylhexane',
  '3-Methylpentane',
  'Acetylene',
  'Ambient Max Temperature',
  'Ambient Min Temperature',
  'Average Ambient Pressure',
  'Average Ambient Temperature',
  'Barometric pressure',
  'Benzene',
  'Carbon monoxide',
  'Cyclohexane',
  'Cyclopentane',
  'Elapsed Sample Time',
  'Ethane',
  'Ethylbenzene',
  'Ethylene',
  'Isobutane',
  'Isopentane',
  'Isoprene',
  'Isopropylbenzene',
  'Methylcyclohexane',
  'Methylcyclopentane',
  'Mixing Height',
  'Nitric oxide (NO)',
  'Nitrogen dioxide (NO2)',
  'Outdoor Temperature',
  'Oxides of nitrogen (NOx)',
  'Ozone',
  'PM10 - LC',
  'PM10 Total 0-10um STP',
  'PM2.5 - Local Conditions',
  'Propane',
  'Propylene',
  'Relative Humidity ',
  'Sample Flow Rate- CV',
  'Sample Max Baro Pressure',
  'Sample Min Baro Pressure',
  'Sample Volume',
  'Solar radiation',
  'Styrene',
  'Sulfur dioxide',
  'Toluene',
  'Total NMOC (non-methane organic compound)',
  'Wind Direction - Scalar',
  'Wind Speed - Scalar',
  'cis-2-Butene',
  'cis-2-Pentene',
  'm-Diethylbenzene',
  'm-Ethyltoluene',
  'm/p Xylene',
  'n-Butane',
  'n-Decane',
  'n-Dodecane',
  'n-Heptane',
  'n-Hexane',
  'n-Nonane',
  'n-Octane',
  'n-Pentane',
  'n-Propylbenzene',
  'n-Undecane',
  'o-Ethyltoluene',
  'o-Xylene',
  'p-Diethylbenzene',
  'p-Ethyltoluene',
  'trans-2-Butene',
  'trans-2-Pentene'},
 'Near Road': {'Ambient Max Temperature',
  'Ambient Min Temperature',
  'Average Ambient Pressure',
  'Average Ambient Temperature',
  'Barometric pressure',
  'Carbon monoxide',
  'Elapsed Sample Time',
  'Nitric oxide (NO)',
  'Nitrogen dioxide (NO2)',
  'Outdoor Temperature',
  'Oxides of nitrogen (NOx)',
  'Ozone',
  'PM2.5 - Local Conditions',
  'Relative Humidity ',
  'Sample Flow Rate- CV',
  'Sample Max Baro Pressure',
  'Sample Min Baro Pressure',
  'Sample Volume',
  'Solar radiation',
  'Wind Direction - Scalar',
  'Wind Speed - Scalar'},
 'Copper View': {'Ambient Max Temperature',
  'Ambient Min Temperature',
  'Average Ambient Pressure',
  'Average Ambient Temperature',
  'Barometric pressure',
  'Carbon monoxide',
  'Elapsed Sample Time',
  'Nitric oxide (NO)',
  'Nitrogen dioxide (NO2)',
  'Outdoor Temperature',
  'Oxides of nitrogen (NOx)',
  'Ozone',
  'PM2.5 - Local Conditions',
  'Relative Humidity ',
  'Sample Flow Rate- CV',
  'Sample Max Baro Pressure',
  'Sample Min Baro Pressure',
  'Sample Volume',
  'Solar radiation',
  'Sulfur dioxide',
  'Wind Direction - Scalar',
  'Wind Speed - Scalar'},
 'STATION LOCATED NEAR INTERSECTION OF 6000 SO & 10000 WEST': {'Barometric pressure',
  'Net radiation',
  'Nitric oxide (NO)',
  'Nitrogen dioxide (NO2)',
  'Outdoor Temperature',
  'Oxides of nitrogen (NOx)',
  'Ozone',
  'Peak Wind Gust',
  'Relative Humidity ',
  'Solar radiation',
  'Temperature Difference',
  'Wind Direction - Scalar',
  'Wind Speed - Scalar'},
 'Dinosaur NM': {'Acceptable PM2.5 AQI & Speciation Mass',
  'Aluminum PM2.5 LC',
  'Ammonium Nitrate PM2.5 LC',
  'Ammonium Sulfate PM2.5 LC',
  'Arsenic PM2.5 LC',
  'Bromine PM2.5 LC',
  'Calcium PM2.5 LC',
  'Chloride PM2.5 LC',
  'Chlorine PM2.5 LC',
  'Chromium PM2.5 LC',
  'Copper PM2.5 LC',
  'EC PM2.5 LC TOR',
  'EC1 PM2.5 LC',
  'EC2 PM2.5 LC',
  'EC3 PM2.5 LC',
  'Iron PM2.5 LC',
  'Lead PM2.5 LC',
  'Light Absorption Coeffiecient',
  'Magnesium PM2.5 LC',
  'Manganese PM2.5 LC',
  'Nickel PM2.5 LC',
  'Nitrite PM2.5 LC',
  'OC PM2.5 LC TOR',
  'OC1 PM2.5 LC',
  'OC2 PM2.5 LC',
  'OC3 PM2.5 LC',
  'OC4 PM2.5 LC',
  'OP PM2.5 LC TOR',
  'Organic Carbon Mass PM2.5 LC',
  'PM10 - LC',
  'PM10-2.5 - Local Conditions',
  'Phosphorus PM2.5 LC',
  'Potassium PM2.5 LC',
  'Rubidium PM2.5 LC',
  'Selenium PM2.5 LC',
  'Silicon PM2.5 LC',
  'Sodium PM2.5 LC',
  'Soil PM2.5 LC',
  'Strontium PM2.5 LC',
  'Sulfate PM2.5 LC',
  'Sulfur PM2.5 LC',
  'Titanium PM2.5 LC',
  'Total Nitrate PM2.5 LC',
  'Vanadium PM2.5 LC',
  'Zinc PM2.5 LC',
  'Zirconium PM2.5 LC'},
 'STATION NEAR INTERSECTION OF WHITEROCK CANYON RD & QURAY CANAL': {'Barometric pressure',
  'Net radiation',
  'Nitric oxide (NO)',
  'Nitrogen dioxide (NO2)',
  'Outdoor Temperature',
  'Oxides of nitrogen (NOx)',
  'Ozone',
  'Peak Wind Gust',
  'Relative Humidity ',
  'Solar radiation',
  'Temperature Difference',
  'Wind Direction - Scalar',
  'Wind Speed - Scalar'},
 'Inland Port': {'Barometric pressure',
  'Black Carbon PM2.5 at 880 nm',
  'Mixing Height',
  'Nitric oxide (NO)',
  'Nitrogen dioxide (NO2)',
  'Outdoor Temperature',
  'Oxides of nitrogen (NOx)',
  'Ozone',
  'PM10 - LC',
  'PM10 Total 0-10um STP',
  'PM2.5 - Local Conditions',
  'Relative Humidity ',
  'Solar radiation',
  'Wind Direction - Scalar',
  'Wind Speed - Scalar'},
 'Bountiful Viewmont': {'1,1,2,2-Tetrachloroethane',
  '1,1,2-Trichloro-1,2,2-trifluoroethane',
  '1,1,2-Trichloroethane',
  '1,1-Dichloroethane',
  '1,1-Dichloroethylene',
  '1,2,3-Trimethylbenzene',
  '1,2,4-Trichlorobenzene',
  '1,2,4-Trimethylbenzene',
  '1,2-Dichlorobenzene',
  '1,2-Dichloropropane',
  '1,3,5-Trimethylbenzene',
  '1,3-Butadiene',
  '1,3-Dichlorobenzene',
  '1,4-Dichlorobenzene',
  '1-Butene',
  '1-Heptene',
  '1-Hexene',
  '1-Nonene',
  '1-Octene',
  '1-Pentene',
  '1-Undecene',
  '2,2,4-Trimethylpentane',
  '2,2-Dimethylbutane',
  '2,3,4-Trimethylpentane',
  '2,3-Dimethylbutane',
  '2,3-Dimethylpentane',
  '2,4-Dimethylpentane',
  '2-2-3-Trimethylpentane',
  '2-Ethyl-1-butene',
  '2-Methyl-1-butene',
  '2-Methyl-1-pentene',
  '2-Methyl-2-butene',
  '2-Methylheptane',
  '2-Methylhexane',
  '2-Methylpentane',
  '3-Methyl-1-butene',
  '3-Methylheptane',
  '3-Methylhexane',
  '3-Methylpentane',
  '4-Methyl-1-pentene',
  'Acenaphthene (TSP) STP',
  'Acenaphthylene (TSP) STP',
  'Acetaldehyde',
  'Acetone',
  'Acetonitrile',
  'Acetylene',
  'Acrolein - Verified',
  'Acrylonitrile',
  'Aluminum PM2.5 LC',
  'Ambient Max Temperature',
  'Ambient Min Temperature',
  'Ammonium Ion PM2.5 LC',
  'Anthracene (TSP) STP',
  'Antimony PM10 STP',
  'Antimony PM2.5 LC',
  'Arsenic PM10 STP',
  'Arsenic PM2.5 LC',
  'Average Ambient Pressure',
  'Average Ambient Pressure for URG3000N',
  'Average Ambient Temperature',
  'Average Ambient Temperature for URG3000N',
  'Barium PM2.5 LC',
  'Barometric pressure',
  'Benzaldehyde',
  'Benzene',
  'Benzo[a]anthracene (TSP) STP',
  'Benzo[a]pyrene (TSP) STP',
  'Benzo[b]fluoranthene (TSP) STP',
  'Benzo[e]pyrene (TSP) STP',
  'Benzo[g,h,i]perylene (TSP) STP',
  'Benzo[k]fluoranthene (TSP) STP',
  'Beryllium PM10 STP',
  'Black Carbon PM2.5 at 880 nm',
  'Bromine PM2.5 LC',
  'Bromochloromethane',
  'Bromodichloromethane',
  'Bromoform',
  'Bromomethane',
  'Butyraldehyde',
  'Cadmium PM10 STP',
  'Cadmium PM2.5 LC',
  'Calcium PM2.5 LC',
  'Carbon disulfide',
  'Carbon tetrachloride',
  'Cerium PM2.5 LC',
  'Cesium PM2.5 LC',
  'Chloride PM2.5 LC',
  'Chlorine PM2.5 LC',
  'Chlorobenzene',
  'Chloroethane',
  'Chloroform',
  'Chloromethane',
  'Chloroprene',
  'Chromium PM10 STP',
  'Chromium PM2.5 LC',
  'Chrysene (TSP) STP',
  'Cobalt PM10 STP',
  'Cobalt PM2.5 LC',
  'Copper PM2.5 LC',
  'Coronene (TSP) STP',
  'Crotonaldehyde',
  'Cyclohexane',
  'Cyclopentane',
  'Cyclopentene',
  'Dibenzo[a,h]anthracene (TSP) STP',
  'Dibromochloromethane',
  'Dichlorodifluoromethane',
  'Dichloromethane',
  'Dodecene',
  'EC CSN_Rev Unadjusted PM2.5 LC TOR',
  'EC CSN_Rev Unadjusted PM2.5 LC TOT',
  'EC PM2.5 LC TOR',
  'EC PM2.5 LC TOT',
  'EC1 CSN_Rev Unadjusted PM2.5 LC',
  'EC1 PM2.5 LC',
  'EC2 CSN_Rev Unadjusted PM2.5 LC',
  'EC2 PM2.5 LC',
  'EC3 CSN_Rev Unadjusted PM2.5 LC',
  'EC3 PM2.5 LC',
  'Elapsed Sample Time',
  'Ethane',
  'Ethyl acrylate',
  'Ethylbenzene',
  'Ethylene',
  'Ethylene dibromide',
  'Ethylene dichloride',
  'Ethylene oxide',
  'Fluoranthene (TSP) STP',
  'Fluorene (TSP) STP',
  'Formaldehyde',
  'Freon 114',
  'Hexachlorobutadiene',
  'Hexanaldehyde',
  'Indeno[1,2,3-cd]pyrene (TSP) STP',
  'Indium PM2.5 LC',
  'Iron PM2.5 LC',
  'Isobutane',
  'Isobutene',
  'Isopentane',
  'Isoprene',
  'Isopropylbenzene',
  'Lead PM10 STP',
  'Lead PM2.5 LC',
  'Light Absorption Coeffiecient',
  'Magnesium PM2.5 LC',
  'Manganese PM10 STP',
  'Manganese PM2.5 LC',
  'Methyl chloroform',
  'Methyl ethyl ketone',
  'Methyl isobutyl ketone',
  'Methyl methacrylate',
  'Methyl tert-butyl ether',
  'Methylcyclohexane',
  'Methylcyclopentane',
  'NOy - NO',
  'Naphthalene (TSP) STP',
  'Nickel PM10 STP',
  'Nickel PM2.5 LC',
  'Nitric oxide (NO)',
  'Nitrogen dioxide (NO2)',
  'OC CSN_Rev Unadjusted PM2.5 LC TOR',
  'OC CSN_Rev Unadjusted PM2.5 LC TOT',
  'OC PM2.5 LC TOR',
  'OC PM2.5 LC TOT',
  'OC1 CSN_Rev Unadjusted PM2.5 LC',
  'OC1 PM2.5 LC',
  'OC2 CSN_Rev Unadjusted PM2.5 LC',
  'OC2 PM2.5 LC',
  'OC3 CSN_Rev Unadjusted PM2.5 LC',
  'OC3 PM2.5 LC',
  'OC4 CSN_Rev Unadjusted PM2.5 LC',
  'OC4 PM2.5 LC',
  'OP CSN_Rev Unadjusted PM2.5 LC TOR',
  'OP CSN_Rev Unadjusted PM2.5 LC TOT',
  'OP PM2.5 LC TOR',
  'OP PM2.5 LC TOT',
  'Outdoor Temperature',
  'Oxides of nitrogen (NOx)',
  'Ozone',
  'PM10 - LC',
  'PM10 Total 0-10um STP',
  'PM2.5 - Local Conditions',
  'Perylene (TSP) STP',
  'Phenanthrene (TSP) STP',
  'Phosphorus PM2.5 LC',
  'Potassium Ion PM2.5 LC',
  'Potassium PM2.5 LC',
  'Propane',
  'Propionaldehyde',
  'Propylene',
  'Propyne',
  'Pyrene (TSP) STP',
  'Reactive oxides of nitrogen (NOy)',
  'Reconstructed Mass PM2.5 LC',
  'Relative Humidity ',
  'Rubidium PM2.5 LC',
  'Sample Flow Rate CV - Nylon Filter',
  'Sample Flow Rate CV - Quartz Filter',
  'Sample Flow Rate CV - Teflon Filter',
  'Sample Flow Rate- CV',
  'Sample Max Baro Pressure',
  'Sample Min Baro Pressure',
  'Sample Volume',
  'Sample Volume - Nylon Filter',
  'Sample Volume - Quartz Filter',
  'Sample Volume - Teflon Filter',
  'Selenium PM10 STP',
  'Selenium PM2.5 LC',
  'Silicon PM2.5 LC',
  'Silver PM2.5 LC',
  'Sodium Ion Pm2.5 LC',
  'Sodium PM2.5 LC',
  'Soil PM2.5 LC',
  'Solar radiation',
  'Strontium PM2.5 LC',
  'Styrene',
  'Sulfate PM2.5 LC',
  'Sulfur PM2.5 LC',
  'Tert-amyl methyl ether',
  'Tetrachloroethylene',
  'Tin PM2.5 LC',
  'Titanium PM2.5 LC',
  'Toluene',
  'Total NMOC (non-methane organic compound)',
  'Total Nitrate PM2.5 LC',
  'Trichloroethylene',
  'Trichlorofluoromethane',
  'Tridecene',
  'Valeraldehyde',
  'Vanadium PM2.5 LC',
  'Vinyl chloride',
  'Wind Direction - Scalar',
  'Wind Speed - Scalar',
  'Zinc PM2.5 LC',
  'Zirconium PM2.5 LC',
  'alpha.-Pinene',
  'beta.-Pinene',
  'cis-1,2-Dichloroethene',
  'cis-1,3-Dichloropropene',
  'cis-2-Butene',
  'cis-2-Hexene',
  'cis-2-Pentene',
  'm-Diethylbenzene',
  'm-Ethyltoluene',
  'm/p Xylene',
  'n-Butane',
  'n-Decane',
  'n-Dodecane',
  'n-Heptane',
  'n-Hexane',
  'n-Nonane',
  'n-Octane',
  'n-Pentane',
  'n-Propylbenzene',
  'n-Tridecane',
  'n-Undecane',
  'o-Ethyltoluene',
  'o-Xylene',
  'p-Diethylbenzene',
  'p-Ethyltoluene',
  'tert-Butyl ethyl ether',
  'trans-1,2-Dichloroethylene',
  'trans-1,3-Dichloropropene',
  'trans-2-Butene',
  'trans-2-Hexene',
  'trans-2-Pentene'},
 'Red Butte': {'1,2,3-Trimethylbenzene',
  '1,2,4-Trimethylbenzene',
  '1,3,5-Trimethylbenzene',
  '1,3-Butadiene',
  '1-Butene',
  '1-Hexene',
  '1-Pentene',
  '2,2,4-Trimethylpentane',

In [14]:
ozone = pd.read_csv("daily_44201_2025.csv")

C:\Users\jmei7\AppData\Local\Temp\ipykernel_18960\3688438501.py:1: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  ozone = pd.read_csv("daily_44201_2025.csv")

In [15]:
ozone.head()

,State Code,County Code,Site Num,Parameter Code,POC,Latitude,Longitude,Datum,Parameter Name,Sample Duration,...,AQI,Method Code,Method Name,Local Site Name,Address,State Name,County Name,City Name,CBSA Name,Date of Last Change
0,1,3,10,44201,1,30.497478,-87.880258,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,...,6.0,87,INSTRUMENTAL - ULTRA VIOLET ABSORPTION,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE...",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2025-10-29
1,1,3,10,44201,1,30.497478,-87.880258,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,...,61.0,87,INSTRUMENTAL - ULTRA VIOLET ABSORPTION,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE...",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2025-10-29
2,1,3,10,44201,1,30.497478,-87.880258,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,...,44.0,87,INSTRUMENTAL - ULTRA VIOLET ABSORPTION,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE...",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2025-10-29
3,1,3,10,44201,1,30.497478,-87.880258,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,...,44.0,87,INSTRUMENTAL - ULTRA VIOLET ABSORPTION,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE...",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2025-10-29
4,1,3,10,44201,1,30.497478,-87.880258,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,...,45.0,87,INSTRUMENTAL - ULTRA VIOLET ABSORPTION,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE...",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2025-10-29

In [16]:
co = pd.read_csv("daily_42101_2025.csv")

C:\Users\jmei7\AppData\Local\Temp\ipykernel_18960\859686527.py:1: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  co = pd.read_csv("daily_42101_2025.csv")

In [17]:
co.head()

,State Code,County Code,Site Num,Parameter Code,POC,Latitude,Longitude,Datum,Parameter Name,Sample Duration,...,AQI,Method Code,Method Name,Local Site Name,Address,State Name,County Name,City Name,CBSA Name,Date of Last Change
0,1,73,23,42101,2,33.553056,-86.815,WGS84,Carbon monoxide,1 HOUR,...,NaN,93,INSTRUMENTAL - GAS FILTER CORRELATION CO ANALYZER,North Birmingham,"NO. B'HAM,SOU R.R., 3009 28TH ST. NO.",Alabama,Jefferson,Birmingham,"Birmingham-Hoover, AL",2025-10-01
1,1,73,23,42101,2,33.553056,-86.815,WGS84,Carbon monoxide,1 HOUR,...,NaN,93,INSTRUMENTAL - GAS FILTER CORRELATION CO ANALYZER,North Birmingham,"NO. B'HAM,SOU R.R., 3009 28TH ST. NO.",Alabama,Jefferson,Birmingham,"Birmingham-Hoover, AL",2025-10-01
2,1,73,23,42101,2,33.553056,-86.815,WGS84,Carbon monoxide,1 HOUR,...,NaN,93,INSTRUMENTAL - GAS FILTER CORRELATION CO ANALYZER,North Birmingham,"NO. B'HAM,SOU R.R., 3009 28TH ST. NO.",Alabama,Jefferson,Birmingham,"Birmingham-Hoover, AL",2025-10-01
3,1,73,23,42101,2,33.553056,-86.815,WGS84,Carbon monoxide,1 HOUR,...,NaN,93,INSTRUMENTAL - GAS FILTER CORRELATION CO ANALYZER,North Birmingham,"NO. B'HAM,SOU R.R., 3009 28TH ST. NO.",Alabama,Jefferson,Birmingham,"Birmingham-Hoover, AL",2025-10-01
4,1,73,23,42101,2,33.553056,-86.815,WGS84,Carbon monoxide,1 HOUR,...,NaN,93,INSTRUMENTAL - GAS FILTER CORRELATION CO ANALYZER,North Birmingham,"NO. B'HAM,SOU R.R., 3009 28TH ST. NO.",Alabama,Jefferson,Birmingham,"Birmingham-Hoover, AL",2025-10-01

In [18]:
no2 = pd.read_csv("daily_42602_2025.csv")

C:\Users\jmei7\AppData\Local\Temp\ipykernel_18960\3336421117.py:1: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  no2 = pd.read_csv("daily_42602_2025.csv")

In [19]:
no2.head()

,State Code,County Code,Site Num,Parameter Code,POC,Latitude,Longitude,Datum,Parameter Name,Sample Duration,...,AQI,Method Code,Method Name,Local Site Name,Address,State Name,County Name,City Name,CBSA Name,Date of Last Change
0,1,73,23,42602,1,33.553056,-86.815,WGS84,Nitrogen dioxide (NO2),1 HOUR,...,31,200,Teledyne-API Model 200EUP or T200UP - Photolyt...,North Birmingham,"NO. B'HAM,SOU R.R., 3009 28TH ST. NO.",Alabama,Jefferson,Birmingham,"Birmingham-Hoover, AL",2025-10-08
1,1,73,23,42602,1,33.553056,-86.815,WGS84,Nitrogen dioxide (NO2),1 HOUR,...,32,200,Teledyne-API Model 200EUP or T200UP - Photolyt...,North Birmingham,"NO. B'HAM,SOU R.R., 3009 28TH ST. NO.",Alabama,Jefferson,Birmingham,"Birmingham-Hoover, AL",2025-10-08
2,1,73,23,42602,1,33.553056,-86.815,WGS84,Nitrogen dioxide (NO2),1 HOUR,...,35,200,Teledyne-API Model 200EUP or T200UP - Photolyt...,North Birmingham,"NO. B'HAM,SOU R.R., 3009 28TH ST. NO.",Alabama,Jefferson,Birmingham,"Birmingham-Hoover, AL",2025-10-08
3,1,73,23,42602,1,33.553056,-86.815,WGS84,Nitrogen dioxide (NO2),1 HOUR,...,12,200,Teledyne-API Model 200EUP or T200UP - Photolyt...,North Birmingham,"NO. B'HAM,SOU R.R., 3009 28TH ST. NO.",Alabama,Jefferson,Birmingham,"Birmingham-Hoover, AL",2025-10-08
4,1,73,23,42602,1,33.553056,-86.815,WGS84,Nitrogen dioxide (NO2),1 HOUR,...,11,200,Teledyne-API Model 200EUP or T200UP - Photolyt...,North Birmingham,"NO. B'HAM,SOU R.R., 3009 28TH ST. NO.",Alabama,Jefferson,Birmingham,"Birmingham-Hoover, AL",2025-10-08

In [20]:
so2 = pd.read_csv("daily_42401_2025.csv")

C:\Users\jmei7\AppData\Local\Temp\ipykernel_18960\1945579195.py:1: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  so2 = pd.read_csv("daily_42401_2025.csv")

In [21]:
so2.head()

,State Code,County Code,Site Num,Parameter Code,POC,Latitude,Longitude,Datum,Parameter Name,Sample Duration,...,AQI,Method Code,Method Name,Local Site Name,Address,State Name,County Name,City Name,CBSA Name,Date of Last Change
0,1,73,23,42401,2,33.553056,-86.815,WGS84,Sulfur dioxide,1 HOUR,...,0.0,100,INSTRUMENTAL - ULTRAVIOLET FLUORESCENCE,North Birmingham,"NO. B'HAM,SOU R.R., 3009 28TH ST. NO.",Alabama,Jefferson,Birmingham,"Birmingham-Hoover, AL",2025-10-02
1,1,73,23,42401,2,33.553056,-86.815,WGS84,Sulfur dioxide,1 HOUR,...,4.0,100,INSTRUMENTAL - ULTRAVIOLET FLUORESCENCE,North Birmingham,"NO. B'HAM,SOU R.R., 3009 28TH ST. NO.",Alabama,Jefferson,Birmingham,"Birmingham-Hoover, AL",2025-10-02
2,1,73,23,42401,2,33.553056,-86.815,WGS84,Sulfur dioxide,1 HOUR,...,3.0,100,INSTRUMENTAL - ULTRAVIOLET FLUORESCENCE,North Birmingham,"NO. B'HAM,SOU R.R., 3009 28TH ST. NO.",Alabama,Jefferson,Birmingham,"Birmingham-Hoover, AL",2025-10-02
3,1,73,23,42401,2,33.553056,-86.815,WGS84,Sulfur dioxide,1 HOUR,...,1.0,100,INSTRUMENTAL - ULTRAVIOLET FLUORESCENCE,North Birmingham,"NO. B'HAM,SOU R.R., 3009 28TH ST. NO.",Alabama,Jefferson,Birmingham,"Birmingham-Hoover, AL",2025-10-02
4,1,73,23,42401,2,33.553056,-86.815,WGS84,Sulfur dioxide,1 HOUR,...,1.0,100,INSTRUMENTAL - ULTRAVIOLET FLUORESCENCE,North Birmingham,"NO. B'HAM,SOU R.R., 3009 28TH ST. NO.",Alabama,Jefferson,Birmingham,"Birmingham-Hoover, AL",2025-10-02

In [22]:
print(ozone.columns == co.columns)
print(ozone.columns == no2.columns)

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True]
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True]

In [23]:
# join on date, location (cbsa, ignore location if absent)

In [24]:
all_param = pd.concat([ozone, co, no2, so2])

In [25]:
len(all_param)

598171

In [26]:
all_param.columns

Index(['State Code', 'County Code', 'Site Num', 'Parameter Code', 'POC',
       'Latitude', 'Longitude', 'Datum', 'Parameter Name', 'Sample Duration',
       'Pollutant Standard', 'Date Local', 'Units of Measure', 'Event Type',
       'Observation Count', 'Observation Percent', 'Arithmetic Mean',
       '1st Max Value', '1st Max Hour', 'AQI', 'Method Code', 'Method Name',
       'Local Site Name', 'Address', 'State Name', 'County Name', 'City Name',
       'CBSA Name', 'Date of Last Change'],
      dtype='object')

In [27]:
set(all_param['CBSA Name'])

{'Adrian, MI',
 'Akron, OH',
 'Albany-Schenectady-Troy, NY',
 'Albuquerque, NM',
 'Allentown-Bethlehem-Easton, PA-NJ',
 'Altoona, PA',
 'Amarillo, TX',
 'Anchorage, AK',
 'Ann Arbor, MI',
 'Appleton, WI',
 'Ardmore, OK',
 'Arkadelphia, AR',
 'Asheville, NC',
 'Ashtabula, OH',
 'Athens-Clarke County, GA',
 'Atlanta-Sandy Springs-Roswell, GA',
 'Atlantic City-Hammonton, NJ',
 'Augusta-Richmond County, GA-SC',
 'Augusta-Waterville, ME',
 'Austin-Round Rock, TX',
 'Bakersfield, CA',
 'Baltimore-Columbia-Towson, MD',
 'Bangor, ME',
 'Baraboo, WI',
 'Barnstable Town, MA',
 'Bartlesville, OK',
 'Baton Rouge, LA',
 'Beaumont-Port Arthur, TX',
 'Beaver Dam, WI',
 'Bellingham, WA',
 'Bemidji, MN',
 'Bennington, VT',
 'Berlin, NH-VT',
 'Big Spring, TX',
 'Billings, MT',
 'Birmingham-Hoover, AL',
 'Bishop, CA',
 'Bismarck, ND',
 'Blacksburg-Christiansburg-Radford, VA',
 'Bloomington, IL',
 'Bloomington, IN',
 'Boise City, ID',
 'Borger, TX',
 'Boston-Cambridge-Newton, MA-NH',
 'Boulder, CO',
 'Bowling Green, KY',
 'Bozeman, MT',
 'Brainerd, MN',
 'Bridgeport-Stamford-Norwalk, CT',
 'Brookings, SD',
 'Brownsville-Harlingen, TX',
 'Brunswick, GA',
 'Buffalo-Cheektowaga-Niagara Falls, NY',
 'Burlington-South Burlington, VT',
 'Cadillac, MI',
 'Cambridge, MD',
 'Canton-Massillon, OH',
 'Cape Coral-Fort Myers, FL',
 'Carlsbad-Artesia, NM',
 'Carson City, NV',
 'Casper, WY',
 'Cedar City, UT',
 'Cedar Rapids, IA',
 'Chambersburg-Waynesboro, PA',
 'Champaign-Urbana, IL',
 'Charleston, WV',
 'Charleston-North Charleston, SC',
 'Charlotte-Concord-Gastonia, NC-SC',
 'Charlottesville, VA',
 'Chattanooga, TN-GA',
 'Cheyenne, WY',
 'Chicago-Naperville-Elgin, IL-IN-WI',
 'Chico, CA',
 'Cincinnati, OH-KY-IN',
 'Claremont-Lebanon, NH-VT',
 'Clarksville, TN-KY',
 'Cleveland, MS',
 'Cleveland-Elyria, OH',
 'Clinton, IA',
 'Coco, PR',
 'College Station-Bryan, TX',
 'Colorado Springs, CO',
 'Columbia, MO',
 'Columbia, SC',
 'Columbus, GA-AL',
 'Columbus, IN',
 'Columbus, OH',
 'Concord, NH',
 'Corning, NY',
 'Corpus Christi, TX',
 'Corsicana, TX',
 'Crestview-Fort Walton Beach-Destin, FL',
 'Dallas-Fort Worth-Arlington, TX',
 'Dalton, GA',
 'Daphne-Fairhope-Foley, AL',
 'Davenport-Moline-Rock Island, IA-IL',
 'Dayton, OH',
 'Decatur, AL',
 'Decatur, IL',
 'Deltona-Daytona Beach-Ormond Beach, FL',
 'Denver-Aurora-Lakewood, CO',
 'Des Moines-West Des Moines, IA',
 'Detroit-Warren-Dearborn, MI',
 'Dickinson, ND',
 'Dover, DE',
 'Duluth, MN-WI',
 'Durango, CO',
 'Durham-Chapel Hill, NC',
 'East Stroudsburg, PA',
 'Eau Claire, WI',
 'Effingham, IL',
 'El Centro, CA',
 'El Paso, TX',
 'Elizabethtown-Fort Knox, KY',
 'Elkhart-Goshen, IN',
 'Enid, OK',
 'Erie, PA',
 'Espa¤ola, NM',
 'Eugene, OR',
 'Eureka-Arcata-Fortuna, CA',
 'Evansville, IN-KY',
 'Fairbanks, AK',
 'Fallon, NV',
 'Fargo, ND-MN',
 'Farmington, NM',
 'Fayetteville, NC',
 'Fayetteville-Springdale-Rogers, AR-MO',
 'Fernley, NV',
 'Findlay, OH',
 'Flagstaff, AZ',
 'Flint, MI',
 'Florence, SC',
 'Fond du Lac, WI',
 'Fort Collins, CO',
 'Fort Payne, AL',
 'Fort Smith, AR-OK',
 'Fort Wayne, IN',
 'Fresno, CA',
 'Gadsden, AL',
 'Gainesville, FL',
 'Gettysburg, PA',
 'Gillette, WY',
 'Glenwood Springs, CO',
 'Grand Island, NE',
 'Grand Junction, CO',
 'Grand Rapids-Wyoming, MI',
 'Greeley, CO',
 'Green Bay, WI',
 'Greenfield Town, MA',
 'Greensboro-High Point, NC',
 'Greenville, NC',
 'Greenville-Anderson-Mauldin, SC',
 'Gulfport-Biloxi-Pascagoula, MS',
 'Hagerstown-Martinsburg, MD-WV',
 'Hanford-Corcoran, CA',
 'Harrisburg-Carlisle, PA',
 'Harrison, AR',
 'Harrisonburg, VA',
 'Hartford-West Hartford-East Hartford, CT',
 'Heber, UT',
 'Helena, MT',
 'Hermiston-Pendleton, OR',
 'Hickory-Lenoir-Morganton, NC',
 'Hilo, HI',
 'Hobbs, NM',
 'Holland, MI',
 'Homosassa Springs, FL',
 'Houma-Thibodaux, LA',
 'Houston-The Woodlands-Sugar Land, TX',
 'Huntington-Ashland, WV-KY-OH',
 'Huntsville, AL',
 'Idaho Falls, ID',
 'Indiana, PA',
 'Indianapolis-Carmel-Anderson, IN',
 'Ithaca, NY',
 'Jackson, MS',
 'Jackson, WY-ID',
 'Jacksonville, FL',
 'Jamestown-Dunkirk-Fredonia, NY',
 'Janesville-Beloit, WI',
 'Jefferson City, MO',
 'Johnstown, PA',
 'Joplin, MO',
 'Kalamazoo-Portage, MI',
 'Kalispell, MT',
 'Kansas City, MO-KS',
 'Kapaa, HI',
 'Keene, NH',
 'Kennewick-Richland, WA',
 'Killeen-Temple, TX',
 'Kingsport-Bristol-Bristol, TN-VA',
 'Kinston, NC',
 'Knoxville, TN',
 'Kokomo, IN',
 'La Crosse-Onalaska, WI-MN',
 'Laconia, NH',
 'Lafayette, LA',
 'Lafayette-West Lafayette, IN',
 'Lake Charles, LA',
 'Lake City, FL',
 'Lakeland-Winter Haven, FL',
 'Lancaster, PA',
 'Lansing-East Lansing, MI',
 'Laramie, WY',
 'Laredo, TX',
 'Las Cruces, NM',
 'Las Vegas-Henderson-Paradise, NV',
 'Lawrence, KS',
 'Lawton, OK',
 'Lebanon, PA',
 'Lewiston-Auburn, ME',
 'Lexington-Fayette, KY',
 'Lima, OH',
 'Lincoln, NE',
 'Little Rock-North Little Rock-Conway, AR',
 'Logan, UT-ID',
 'Longview, TX',
 'Los Angeles-Long Beach-Anaheim, CA',
 'Louisville/Jefferson County, KY-IN',
 'Ludington, MI',
 'Macon, GA',
 'Madera, CA',
 'Madison, WI',
 'Manchester-Nashua, NH',
 'Manitowoc, WI',
 'Mankato-North Mankato, MN',
 'Marietta, OH',
 'Marshall, MN',
 'Marshall, TX',
 'Mayaguez, PR',
 'McAlester, OK',
 'McAllen-Edinburg-Mission, TX',
 'Medford, OR',
 'Memphis, TN-MS-AR',
 'Merced, CA',
 'Meridian, MS',
 'Miami, OK',
 'Miami-Fort Lauderdale-West Palm Beach, FL',
 'Michigan City-La Porte, IN',
 'Middlesborough, KY',
 'Milwaukee-Waukesha-West Allis, WI',
 'Minneapolis-St. Paul-Bloomington, MN-WI',
 'Minot, ND',
 'Missoula, MT',
 'Mobile, AL',
 'Modesto, CA',
 'Monroe, LA',
 'Montgomery, AL',
 'Morehead City, NC',
 'Morgantown, WV',
 'Morristown, TN',
 'Mount Pleasant, TX',
 'Mount Vernon, IL',
 'Mount Vernon, OH',
 'Muncie, IN',
 'Muscatine, IA',
 'Muskegon, MI',
 'Myrtle Beach-Conway-North Myrtle Beach, SC-NC',
 'Naples-Immokalee-Marco Island, FL',
 'Nashville-Davidson--Murfreesboro--Franklin, TN',
 'New Haven-Milford, CT',
 'New Orleans-Metairie, LA',
 'New York-Newark-Jersey City, NY-NJ-PA',
 'Niles-Benton Harbor, MI',
 'North Port-Sarasota-Bradenton, FL',
 'Norwich-New London, CT',
 'Ocala, FL',
 'Ogden-Clearfield, UT',
 'Ogdensburg-Massena, NY',
 'Oklahoma City, OK',
 'Olympia-Tumwater, WA',
 'Omaha-Council Bluffs, NE-IA',
 'Orlando-Kissimmee-Sanford, FL',
 'Ottawa-Peru, IL',
 'Owensboro, KY',
 'Oxford, NC',
 'Oxnard-Thousand Oaks-Ventura, CA',
 'Paducah, KY-IL',
 'Palatka, FL',
 'Palm Bay-Melbourne-Titusville, FL',
 'Panama City, FL',
 'Parkersburg-Vienna, WV',
 'Payson, AZ',
 'Pensacola-Ferry Pass-Brent, FL',
 'Peoria, IL',
 'Philadelphia-Camden-Wilmington, PA-NJ-DE-MD',
 'Phoenix-Mesa-Scottsdale, AZ',
 'Pittsburgh, PA',
 'Pittsfield, MA',
 'Pocatello, ID',
 'Point Pleasant, WV-OH',
 'Ponca City, OK',
 'Ponce, PR',
 'Port Angeles, WA',
 'Port St. Lucie, FL',
 'Portland-South Portland, ME',
 'Portland-Vancouver-Hillsboro, OR-WA',
 'Portsmouth, OH',
 'Prescott, AZ',
 'Price, UT',
 'Providence-Warwick, RI-MA',
 'Provo-Orem, UT',
 'Pueblo, CO',
 'Quincy, IL-MO',
 'Racine, WI',
 'Raleigh, NC',
 'Rapid City, SD',
 'Reading, PA',
 'Red Bluff, CA',
 'Red Wing, MN',
 'Redding, CA',
 'Reno, NV',
 'Richmond, VA',
 'Riverside-San Bernardino-Ontario, CA',
 'Riverton, WY',
 'Roanoke, VA',
 'Rochester, MN',
 'Rochester, NY',
 'Rock Springs, WY',
 'Rockford, IL',
 'Rockland, ME',
 'Rocky Mount, NC',
 'Rutland, VT',
 'Sacramento--Roseville--Arden-Arcade, CA',
 'Salem, OR',
 'Salinas, CA',
 'Salisbury, MD-DE',
 'Salt Lake City, UT',
 'San Antonio-New Braunfels, TX',
 'San Diego-Carlsbad, CA',
 'San Jose-Sunnyvale-Santa Clara, CA',
 'San Juan-Carolina-Caguas, PR',
 'San Luis Obispo-Paso Robles-Arroyo Grande, CA',
 'Santa Cruz-Watsonville, CA',
 'Santa Fe, NM',
 'Santa Maria-Santa Barbara, CA',
 'Savannah, GA',
 'Sayre, PA',
 'Scranton--Wilkes-Barre--Hazleton, PA',
 'Seattle-Tacoma-Bellevue, WA',
 'Sebastian-Vero Beach, FL',
 'Sebring, FL',
 'Sevierville, TN',
 'Sheboygan, WI',
 'Sheridan, WY',
 'Shreveport-Bossier City, LA',
 'Sierra Vista-Douglas, AZ',
 'Sioux City, IA-NE-SD',
 'Sioux Falls, SD',
 'Somerset, KY',
 'Somerset, PA',
 'Sonora, CA',
 'South Bend-Mishawaka, IN-MI',
 'Spartanburg, SC',
 'Spokane-Spokane Valley, WA',
 'Springfield, IL',
 'Springfield, MA',
 'Springfield, MO',
 'Springfield, OH',
 'St. Cloud, MN',
 'St. George, UT',
 'St. Joseph, MO-KS',
 'St. Louis, MO-IL',
 'St. Marys, PA',
 'State College, PA',
 'Stockton-Lodi, CA',
 'Syracuse, NY',
 'Tallahassee, FL',
 'Tampa-St. Petersburg-Clearwater, FL',
 'Terre Haute, IN',
 'Toledo, OH',
 'Topeka, KS',
 'Torrington, CT',
 'Traverse City, MI',
 'Trenton, NJ',
 'Truckee-Grass Valley, CA',
 'Tucson, AZ',
 'Tulsa, OK',
 'Tupelo, MS',
 'Tuscaloosa, AL',
 'Tyler, TX',
 'Urban Honolulu, HI',
 'Vallejo-Fairfield, CA',
 'Vermillion, SD',
 'Vernal, UT',
 'Victoria, TX',
 'Vincennes, IN',
 'Vineland-Bridgeton, NJ',
 'Vineyard Haven, MA',
 'Virginia Beach-Norfolk-Newport News, VA-NC',
 'Visalia-Porterville, CA',
 'Wabash, IN',
 'Waco, TX',
 'Walla Walla, WA',
 'Warren, PA',
 'Washington, NC',
 'Washington-Arlington-Alexandria, DC-VA-MD-WV',
 'Waterloo-Cedar Falls, IA',
 'Watertown, SD',
 'Watertown-Fort Atkinson, WI',
 'Watertown-Fort Drum, NY',
 'Wausau, WI',
 'Weirton-Steubenville, WV-OH',
 'Wheeling, WV-OH',
 'Whitewater-Elkhorn, WI',
 'Wichita, KS',
 'Williamsport, PA',
 'Williston, ND',
 'Wilmington, NC',
 'Wilmington, OH',
 'Winchester, VA-WV',
 'Winston-Salem, NC',
 'Worcester, MA-CT',
 'York-Hanover, PA',
 'Youngstown-Warren-Boardman, OH-PA',
 'Yuba City, CA',
 'Yuma, AZ',
 nan}

In [28]:
all_param.sort_values("Date Local").head()

,State Code,County Code,Site Num,Parameter Code,POC,Latitude,Longitude,Datum,Parameter Name,Sample Duration,...,AQI,Method Code,Method Name,Local Site Name,Address,State Name,County Name,City Name,CBSA Name,Date of Last Change
58201,12,57,81,44201,1,27.740033,-82.465146,WGS84,Ozone,8-HR RUN AVG BEGIN HOUR,...,37.0,47,INSTRUMENTAL - ULTRA VIOLET,Simmons Park,2401 19th Avenue Northwest,Florida,Hillsborough,Ruskin,"Tampa-St. Petersburg-Clearwater, FL",2025-11-17
47948,34,39,4,42602,2,40.641440,-74.208365,WGS84,Nitrogen dioxide (NO2),1 HOUR,...,30.0,74,INSTRUMENTAL - CHEMILUMINESCENCE,Elizabeth Lab,NJ Turnpike Interchange 13 Toll Plaza,New Jersey,Union,Elizabeth,"New York-Newark-Jersey City, NY-NJ-PA",2025-09-30
47612,8,69,11,44201,1,40.592543,-105.141122,WGS84,Ozone,8-HR RUN AVG BEGIN HOUR,...,25.0,199,Instrumental - Chemiluminescence API Model 265...,FORT COLLINS - WEST,3416 LA PORTE AVE.,Colorado,Larimer,Fort Collins,"Fort Collins, CO",2025-11-07
43962,26,163,99,42101,1,42.295824,-83.129431,WGS84,Carbon monoxide,8-HR RUN AVG END HOUR,...,2.0,54,INSTRUMENTAL - NONDISPERSIVE INFRARED,TRINITY ST MARKS - Gordy Howe International Br...,9191 W FORT ST (Detroit-Trinity),Michigan,Wayne,Detroit,"Detroit-Warren-Dearborn, MI",2025-09-17
25832,6,61,3,44201,1,38.935680,-121.099590,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,...,18.0,87,INSTRUMENTAL - ULTRA VIOLET ABSORPTION,Auburn-Atwood,"11645 Atwood Street, Auburn",California,Placer,Auburn,"Sacramento--Roseville--Arden-Arcade, CA",2025-10-23

In [29]:
print(all_param.iloc[:, 10:].head())

  Pollutant Standard  Date Local   Units of Measure Event Type  \
0  Ozone 8-hour 2015  2025-02-28  Parts per million        NaN
1  Ozone 8-hour 2015  2025-03-01  Parts per million        NaN
2  Ozone 8-hour 2015  2025-03-02  Parts per million        NaN
3  Ozone 8-hour 2015  2025-03-03  Parts per million        NaN
4  Ozone 8-hour 2015  2025-03-04  Parts per million        NaN

   Observation Count  Observation Percent  Arithmetic Mean  1st Max Value  \
0                  1                  6.0         0.006000          0.006
1                 17                100.0         0.050824          0.058
2                 17                100.0         0.038882          0.047
3                 17                100.0         0.042765          0.048
4                 17                100.0         0.046000          0.049

   1st Max Hour   AQI  Method Code                             Method Name  \
0            23   6.0           87  INSTRUMENTAL - ULTRA VIOLET ABSORPTION
1            10  61.0           87  INSTRUMENTAL - ULTRA VIOLET ABSORPTION
2            10  44.0           87  INSTRUMENTAL - ULTRA VIOLET ABSORPTION
3             9  44.0           87  INSTRUMENTAL - ULTRA VIOLET ABSORPTION
4             9  45.0           87  INSTRUMENTAL - ULTRA VIOLET ABSORPTION

     Local Site Name                                            Address  \
0  FAIRHOPE, Alabama  FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE...
1  FAIRHOPE, Alabama  FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE...
2  FAIRHOPE, Alabama  FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE...
3  FAIRHOPE, Alabama  FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE...
4  FAIRHOPE, Alabama  FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE...

  State Name County Name City Name                  CBSA Name  \
0    Alabama     Baldwin  Fairhope  Daphne-Fairhope-Foley, AL
1    Alabama     Baldwin  Fairhope  Daphne-Fairhope-Foley, AL
2    Alabama     Baldwin  Fairhope  Daphne-Fairhope-Foley, AL
3    Alabama     Baldwin  Fairhope  Daphne-Fairhope-Foley, AL
4    Alabama     Baldwin  Fairhope  Daphne-Fairhope-Foley, AL

  Date of Last Change
0          2025-10-29
1          2025-10-29
2          2025-10-29
3          2025-10-29
4          2025-10-29

In [39]:
choose = ["Date Local", 'Latitude', 'Longitude', 'Sample Duration',
         'Parameter Name', 'Observation Count', "Observation Percent", 'Arithmetic Mean', '1st Max Value', '1st Max Hour',
          "State Name", "County Name", "City Name", "CBSA Name"]

In [36]:
all_param[choose].head()

,Latitude,Longitude,Sample Duration,Parameter Name,State Name,Date Local,Observation Count,Observation Percent,Arithmetic Mean,1st Max Value,1st Max Hour,County Name,City Name,CBSA Name,Date of Last Change
0,30.497478,-87.880258,8-HR RUN AVG BEGIN HOUR,Ozone,Alabama,2025-02-28,1,6.0,0.006000,0.006,23,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2025-10-29
1,30.497478,-87.880258,8-HR RUN AVG BEGIN HOUR,Ozone,Alabama,2025-03-01,17,100.0,0.050824,0.058,10,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2025-10-29
2,30.497478,-87.880258,8-HR RUN AVG BEGIN HOUR,Ozone,Alabama,2025-03-02,17,100.0,0.038882,0.047,10,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2025-10-29
3,30.497478,-87.880258,8-HR RUN AVG BEGIN HOUR,Ozone,Alabama,2025-03-03,17,100.0,0.042765,0.048,9,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2025-10-29
4,30.497478,-87.880258,8-HR RUN AVG BEGIN HOUR,Ozone,Alabama,2025-03-04,17,100.0,0.046000,0.049,9,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2025-10-29

In [37]:
all_param.sort_values("CBSA Name").head()

,State Code,County Code,Site Num,Parameter Code,POC,Latitude,Longitude,Datum,Parameter Name,Sample Duration,...,AQI,Method Code,Method Name,Local Site Name,Address,State Name,County Name,City Name,CBSA Name,Date of Last Change
124833,26,91,7,44201,1,41.995568,-83.946559,WGS84,Ozone,8-HR RUN AVG BEGIN HOUR,...,51.0,87,INSTRUMENTAL - ULTRA VIOLET ABSORPTION,"6792 RAISIN CENTER HWY, LENAWEE CO.RD.COMM.OWN...",6792 RAISEN CTR HWY (TECUMSEH),Michigan,Lenawee,Tecumseh,"Adrian, MI",2025-11-14
124832,26,91,7,44201,1,41.995568,-83.946559,WGS84,Ozone,8-HR RUN AVG BEGIN HOUR,...,74.0,87,INSTRUMENTAL - ULTRA VIOLET ABSORPTION,"6792 RAISIN CENTER HWY, LENAWEE CO.RD.COMM.OWN...",6792 RAISEN CTR HWY (TECUMSEH),Michigan,Lenawee,Tecumseh,"Adrian, MI",2025-11-14
124831,26,91,7,44201,1,41.995568,-83.946559,WGS84,Ozone,8-HR RUN AVG BEGIN HOUR,...,40.0,87,INSTRUMENTAL - ULTRA VIOLET ABSORPTION,"6792 RAISIN CENTER HWY, LENAWEE CO.RD.COMM.OWN...",6792 RAISEN CTR HWY (TECUMSEH),Michigan,Lenawee,Tecumseh,"Adrian, MI",2025-11-14
124830,26,91,7,44201,1,41.995568,-83.946559,WGS84,Ozone,8-HR RUN AVG BEGIN HOUR,...,32.0,87,INSTRUMENTAL - ULTRA VIOLET ABSORPTION,"6792 RAISIN CENTER HWY, LENAWEE CO.RD.COMM.OWN...",6792 RAISEN CTR HWY (TECUMSEH),Michigan,Lenawee,Tecumseh,"Adrian, MI",2025-11-14
124829,26,91,7,44201,1,41.995568,-83.946559,WGS84,Ozone,8-HR RUN AVG BEGIN HOUR,...,47.0,87,INSTRUMENTAL - ULTRA VIOLET ABSORPTION,"6792 RAISIN CENTER HWY, LENAWEE CO.RD.COMM.OWN...",6792 RAISEN CTR HWY (TECUMSEH),Michigan,Lenawee,Tecumseh,"Adrian, MI",2025-11-14

In [33]:
all_param[all_param["CBSA Name"] == 'Daphne-Fairhope-Foley, AL']

,State Code,County Code,Site Num,Parameter Code,POC,Latitude,Longitude,Datum,Parameter Name,Sample Duration,...,AQI,Method Code,Method Name,Local Site Name,Address,State Name,County Name,City Name,CBSA Name,Date of Last Change
0,1,3,10,44201,1,30.497478,-87.880258,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,...,6.0,87,INSTRUMENTAL - ULTRA VIOLET ABSORPTION,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE...",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2025-10-29
1,1,3,10,44201,1,30.497478,-87.880258,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,...,61.0,87,INSTRUMENTAL - ULTRA VIOLET ABSORPTION,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE...",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2025-10-29
2,1,3,10,44201,1,30.497478,-87.880258,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,...,44.0,87,INSTRUMENTAL - ULTRA VIOLET ABSORPTION,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE...",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2025-10-29
3,1,3,10,44201,1,30.497478,-87.880258,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,...,44.0,87,INSTRUMENTAL - ULTRA VIOLET ABSORPTION,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE...",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2025-10-29
4,1,3,10,44201,1,30.497478,-87.880258,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,...,45.0,87,INSTRUMENTAL - ULTRA VIOLET ABSORPTION,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE...",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2025-10-29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,1,3,10,44201,1,30.497478,-87.880258,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,...,39.0,87,INSTRUMENTAL - ULTRA VIOLET ABSORPTION,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE...",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2025-10-29
179,1,3,10,44201,1,30.497478,-87.880258,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,...,51.0,87,INSTRUMENTAL - ULTRA VIOLET ABSORPTION,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE...",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2025-10-29
180,1,3,10,44201,1,30.497478,-87.880258,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,...,23.0,87,INSTRUMENTAL - ULTRA VIOLET ABSORPTION,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE...",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2025-10-29
181,1,3,10,44201,1,30.497478,-87.880258,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,...,31.0,87,INSTRUMENTAL - ULTRA VIOLET ABSORPTION,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE...",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2025-10-29
182,1,3,10,44201,1,30.497478,-87.880258,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,...,34.0,87,INSTRUMENTAL - ULTRA VIOLET ABSORPTION,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE...",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",2025-10-29

In [41]:
all_param[choose].to_csv("all_parameters_daily.csv", index=False)